#include <my_headers.mqh>
#include <stdlib.mqh>
#include <inputs_common.mqh>
//#include <inputs_mine_only.mqh>
#include <inputs_mine_tovariable_for_clients.mqh>
#include <variables_all.mqh>
bool itisme_sachin=False;
#include <skraj_all_functions.mqh>
#include <skraj_main_system_functions.mqh>
